import { useSpring, animated } from 'react-spring';
import Link from './components/Link';
import Htn from './assets/htn.svg';
import Bobbinet from './assets/bobbinet.svg';
import Habba from './assets/habba.svg';
import Abit from './assets/abit.svg';
import Allay from './assets/allay.svg';
import Engposts from './assets/engposts.svg';
import Orakl from './assets/orakl.svg';
import Funnel from './assets/funnel.svg';
import Bot from './assets/bot.svg';
import Dodoer from './assets/dodoer.svg';
import Portrait from './assets/portrait.png';
import Blob from './assets/blob.webm';

function App() {
  const contentStyles = useSpring({
    delay: 1500,
    to: [{ opacity: 1 }],
    from: { opacity: 0 },
  });

  const titleStyles = useSpring({
    delay: 500,
    to: [{ opacity: 1 }],
    from: { opacity: 0 },
  });

  const projects = [
    {
      title: 'Habba',
      image: Habba,
      link: 'https://habba.app',
      vc: 'https://vc.ru/tribuna/494193-habba-ocheredi-bez-lishnego',
      comment: 'Electronic queues made super easy',
      soon: false,
    },
    {
      title: 'HTN Coach',
      subtitle: 'in pilot',
      image: Htn,
      link: 'https://htn.ai',
      soon: false,
      comment:
        'Service for monitoring patients with chronic diseases of the cardiovascular system in partnership with Omron',
    },
    {
      title: 'Orakl Lab',
      image: Orakl,
      link: 'https://orakllab.xyz/',
      comment: 'Decentralized zero-knowledge wellness proof solutions',
      soon: false,
    },
    {
      title: 'Bobbinet',
      image: Bobbinet,
      link: 'https://bobbinet.com',
      comment: 'Decentralized health 4.0 application powered by AI',
      soon: false,
    },
    {
      title: 'Dodoer',
      subtitle: 'coming soon',
      image: Dodoer,
      comment: 'The one and only place for your startups',
      soon: false,
    },
    {
      title: 'Abit',
      subtitle: 'in pilot',
      image: Abit,
      comment: 'University highload database solutions',
      soon: false,
    },
    {
      title: 'Allay',
      subtitle: 'coming soon',
      image: Allay,
      comment:
        'Application to support patients with chronic pain by generating sounds generated by ML',
      soon: false,
    },
    {
      title: 'EngPosts',
      image: Engposts,
      link: 'https://engposts.com',
      comment:
        'Flashcards that increase vocabulary, improve pronunciation and develop listening comprehension',
      soon: false,
    },
    {
      title: 'Open Funnels',
      subtitle: 'open-source',
      image: Funnel,
      link: 'https://github.com/Borodutch/open-funnels-backend',
      comment:
        'Open-source solutions for intuitive way of tracking and analyzing user behavior',
      soon: false,
    },
    {
      title: 'Bot finder',
      subtitle: 'open-source',
      image: Bot,
      link: 'https://github.com/Borodutch/bot-finder',
      comment: 'Web extension for vc.ru, TJ and DTF',
      soon: false,
    },
  ];

  return (
    <>
      <video
        src={Blob}
        autoPlay
        loop
        muted
        className="absolute top-0 left-0 h-screen w-screen object-cover"
      />
      <div className="flex h-screen flex-col">
        <div className="relative flex flex-1 flex-col items-center justify-center py-10">
          <animated.div style={titleStyles} className="mt-10 px-5">
            <img
              src={Portrait}
              className="mx-auto mb-5 h-60 w-60 rounded-full"
            />
            <h1 className="break-words text-center text-3xl font-light text-gray-700 md:text-4xl">
              Hello, I am{' '}
              <span className="bg-gradient-to-r from-green-600 to-sky-600 bg-clip-text font-medium text-transparent">
                Stanislav Nepomniashchikh.
              </span>
            </h1>
            <div className="pt-3 text-center text-xl font-light text-black text-opacity-40 md:text-2xl">
              Developer.
            </div>
            <div className="flex break-before-all flex-col items-center justify-center space-y-2 pt-10 text-xl font-light text-gray-700 md:flex-row md:space-x-5 md:space-y-0 md:text-2xl">
              <Link to="https://t.me/stasnblog">blog</Link>
              <Link to="https://t.me/stasnepom">telegram</Link>
              <Link to="https://github.com/stasnepomn">github</Link>
              <Link to="mailto:contact@stasn.me" dashed>
                contact@stasn.me
              </Link>
            </div>
          </animated.div>
          <animated.div style={contentStyles} className="w-full">
            <div className="mt-14 w-full break-words">
              <main className="mx-auto grid max-w-screen-lg grid-cols-1 flex-col items-start justify-center gap-5 md:grid-cols-2">
                {projects.map((project) => (
                  <div className="flex w-full flex-row space-x-5 rounded-lg bg-white bg-opacity-20 p-5 shadow-sm backdrop-blur-md">
                    <div className="flex min-w-fit items-center justify-center md:items-start">
                      {project.soon ? (
                        <img
                          src={project.image}
                          alt={project.title}
                          className="grayscale"
                          width={70}
                          height={70}
                        />
                      ) : (
                        <img
                          src={project.image}
                          alt={project.title}
                          width={70}
                          height={70}
                        />
                      )}
                    </div>
                    <div className="flex flex-col space-y-1">
                      <div className="text-lg font-medium opacity-80 md:text-xl">
                        {project.title}
                        {project.link && (
                          <a
                            href={project.link}
                            target="_blank"
                            className="ml-2 border-b-2 border-sky-700 border-opacity-40 font-normal text-sky-700 transition-all hover:opacity-60"
                          >
                            check out
                          </a>
                        )}
                        {project.vc && (
                          <a
                            href={project.vc}
                            target="_blank"
                            className="ml-2 border-b-2 border-sky-700 border-opacity-40 font-normal text-sky-700 transition-all hover:opacity-60"
                          >
                            VC.ru
                          </a>
                        )}
                        {project.subtitle && (
                          <span className="ml-2 font-light opacity-50">
                            {project.subtitle}
                          </span>
                        )}
                      </div>
                      <div className="text-md opacity-50 md:text-lg">
                        {project.comment}
                      </div>
                    </div>
                  </div>
                ))}
              </main>
            </div>
          </animated.div>
        </div>
      </div>
    </>
  );
}

export default App;
