export const projects = [
  {
    title: 'Stigma',
    link: 'https://stigmacare.com/',
    stack: '',
    comment: 'The only weight loss service that supports and guides you',
  },
  {
    title: 'Habba Go',
    link: 'https://habba.app',
    posts: [
      {
        title: 'vc.ru',
        href: 'https://vc.ru/tribuna/494193-habba-ocheredi-bez-lishnego',
      },
    ],
    stack: 'Preact, Koa, MongoDB, YooKassa',
    comment: 'Electronic queues made super easy',
  },
  // {
  //   title: 'TimeCross',
  //   subtitle: 'release soon',
  //   image: TimeCross,
  //   stack: 'Ruby on Rails, Turbo Streams',
  //   comment: 'Time management for remote teams',
  // },
  // {
  //   title: 'VelvetMind',
  //   subtitle: 'open-source',
  //   link: 'https://velvetmind.space/',
  //   comment: 'Your personal encrypted diary',
  //   stack: 'React, Koa, MongoDB',
  // },
  // {
  //   title: 'Dodoer',
  //   subtitle: 'release soon',
  //   image: Dodoer,
  //   comment: 'The best place to fund your startups',
  // },
  {
    title: 'HTN Coach',
    link: 'https://htn.ai',
    stack: 'React, NestJS, MongoDB, Flask (microservices), Redis, Flutter',
    comment:
      'Service for monitoring patients with chronic diseases of the cardiovascular system in partnership with Omron',
  },
  {
    title: 'Palme',
    link: 'https://www.palmeschool.com/',
    stack: 'Yii2, MySQL, Box, Stripe',
    comment: 'Online Russian language school in the USA and Canada',
  },
  {
    title: 'Todorant',
    link: 'https://todorant.com/',
    stack: 'TypeScript, Vue2, Koa, MongoDB',
    comment: 'Smart to-do app that will help you get your tasks done faster',
  },
  // {
  //   title: 'Orakl Lab',
  //   subtitle: 'pilot soon',
  //   image: Orakl,
  //   link: 'https://orakllab.xyz/',
  //   comment: 'Decentralized zero-knowledge wellness proof solutions',
  // },
  // {
  //   title: 'Bobbinet',
  //   image: Bobbinet,
  //   subtitle: 'pilot soon',
  //   link: 'https://bobbinet.com',
  //   comment: 'Decentralized health 4.0 application powered by AI',
  //   stack: 'Solidity, TypeScript, Flutter',
  // },
  // {
  //   title: 'Abit',
  //   subtitle: 'info soon',
  //   image: Abit,
  //   stack: 'Django 4, Vue 2, Redis, NestJS (microservices), PostgreSQL',
  //   comment: 'University highload database solutions',
  // },
  // {
  //   title: 'Allay',
  //   subtitle: 'coming soon',
  //   image: Allay,
  //   comment:
  //     'Application to support patients with chronic pain by generating sounds generated by ML',
  //   stack: 'Python, scikit-learn, PostgreSQL, Flutter',
  // },
  {
    title: 'EngPosts',
    stack: 'Vue 2, Koa, MongoDB, Strapi',
    link: 'https://engposts.com',
    comment:
      'Flashcards that increase vocabulary, improve pronunciation and develop listening comprehension',
  },
  {
    title: 'Open Funnels',
    subtitle: 'open source',
    stack: 'NestJS, Vue 2, MongoDB',
    posts: [
      {
        title: 'backend',
        href: 'https://github.com/Borodutch/open-funnels-backend',
      },
      {
        title: 'frontend',
        href: 'https://github.com/Borodutch/open-funnels-frontend',
      },
    ],
    comment:
      'Open-source solutions for intuitive way of tracking and analyzing user behavior',
  },
  {
    title: 'Bot finder',
    subtitle: 'open source',
    stack: 'JavaScript',
    link: 'https://github.com/Borodutch/bot-finder',
    comment: 'Browser extension for vc.ru, TJ and DTF',
  },
];
